# Server configuration
server.port=${PORT:8080}

# Primary datasource (Local PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/comicop
spring.datasource.username=postgres
spring.datasource.password=1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.messages.basename=i18n/messages
spring.thymeleaf.encoding=UTF-8