CREATE SEQUENCE IF NOT EXISTS category_id_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS product_id_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS users_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE cart
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT,
    total_price DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_cart PRIMARY KEY (id)
);

CREATE TABLE cart_item
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id BIGINT,
    quantity   INTEGER                                 NOT NULL,
    cart_id    BIGINT,
    CONSTRAINT pk_cartitem PRIMARY KEY (id)
);

CREATE TABLE category
(
    category_id   BIGINT       NOT NULL,
    category_name VARCHAR(255) NOT NULL,
    category_desc VARCHAR(255),
    CONSTRAINT pk_category PRIMARY KEY (category_id)
);

CREATE TABLE file_data
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    type      VARCHAR(255),
    file_path VARCHAR(255),
    file_size BIGINT,
    CONSTRAINT pk_file_data PRIMARY KEY (id)
);

CREATE TABLE "order"
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          BIGINT,
    order_date       TIMESTAMP WITHOUT TIME ZONE,
    total_amount     DOUBLE PRECISION                        NOT NULL,
    shipping_address VARCHAR(255),
    payment_method   VARCHAR(255),
    status           VARCHAR(255),
    CONSTRAINT pk_order PRIMARY KEY (id)
);

CREATE TABLE order_item
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id BIGINT,
    quantity   INTEGER                                 NOT NULL,
    order_id   BIGINT,
    CONSTRAINT pk_orderitem PRIMARY KEY (id)
);

CREATE TABLE product
(
    product_id   BIGINT           NOT NULL,
    product_name VARCHAR(255),
    price        DOUBLE PRECISION NOT NULL,
    qty_in_stock INTEGER,
    product_desc VARCHAR(255),
    image_id     BIGINT,
    CONSTRAINT pk_product PRIMARY KEY (product_id)
);

CREATE TABLE product_category
(
    category_id BIGINT NOT NULL,
    product_id  BIGINT NOT NULL,
    CONSTRAINT pk_product_category PRIMARY KEY (category_id, product_id)
);

CREATE TABLE users
(
    id                      BIGINT       NOT NULL,
    username                VARCHAR(255) NOT NULL,
    email                   VARCHAR(255) NOT NULL,
    password                VARCHAR(255) NOT NULL,
    verification_code       VARCHAR(255),
    verification_expiration TIMESTAMP WITHOUT TIME ZONE,
    enabled                 BOOLEAN      NOT NULL,
    role                    VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE cart
    ADD CONSTRAINT uc_cart_user UNIQUE (user_id);

ALTER TABLE category
    ADD CONSTRAINT uc_category_category_name UNIQUE (category_name);

ALTER TABLE product
    ADD CONSTRAINT uc_product_image UNIQUE (image_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE cart_item
    ADD CONSTRAINT FK_CARTITEM_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (id);

ALTER TABLE cart_item
    ADD CONSTRAINT FK_CARTITEM_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (product_id);

ALTER TABLE cart
    ADD CONSTRAINT FK_CART_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE order_item
    ADD CONSTRAINT FK_ORDERITEM_ON_ORDER FOREIGN KEY (order_id) REFERENCES "order" (id);

ALTER TABLE order_item
    ADD CONSTRAINT FK_ORDERITEM_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (product_id);

ALTER TABLE "order"
    ADD CONSTRAINT FK_ORDER_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_IMAGE FOREIGN KEY (image_id) REFERENCES file_data (id);

ALTER TABLE product_category
    ADD CONSTRAINT fk_procat_on_category FOREIGN KEY (category_id) REFERENCES category (category_id);

ALTER TABLE product_category
    ADD CONSTRAINT fk_procat_on_product FOREIGN KEY (product_id) REFERENCES product (product_id);